version: "3"

services: 
    flask_api:
        build: ./flask_api
        restart: unless-stopped
        expose:
          - 5000
        depends_on: 
            - redis
            - rq_worker
        links: 
            - redis

    rq_worker:
        build: ./flask_api
        command: rq worker --url redis://redis:6379 rq_worker
        depends_on: 
            - redis
        links: 
            - redis
        restart: unless-stopped

    redis:
        image: redis:alpine
        expose:
            - 6379
        restart: unless-stopped
    nginx:
        build: ./nginx
        depends_on:
          - flask_api
        restart: unless-stopped
        links:
          - flask_api
        ports:
          - 80:80
          - 443:443
